import {useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
type Alert={severity:"High"|"Medium"|"Low";title:string;detail:string;time:string};
type Result={metric:string;horizonDays:number;forecast:{value:number;confidence:number};provenance:{modelVersion:string}};
const alerts:Alert[]=[{severity:"High",title:"Receivables concentration increased",detail:"Two enterprise accounts now represent a larger share of open receivables.",time:"12m ago"},{severity:"Medium",title:"Revenue trend changed",detail:"Recent observations diverge from the previous baseline.",time:"1h ago"},{severity:"Low",title:"Data connector healthy",detail:"All configured demo connectors reported successfully.",time:"3h ago"}];
const tabs=["Overview","Intelligence","Reports","Alerts","Data","Workflows","Settings"];
const connectors=[["Stripe Finance","Synced 2 min ago"],["Salesforce","Synced 8 min ago"],["Shopify","Synced 14 min ago"]] as const;
function App(){const[tab,setTab]=useState("Overview");const[status,setStatus]=useState("Checking");const[scan,setScan]=useState("Run intelligence scan");const[result,setResult]=useState<Result|null>(null);const[query,setQuery]=useState("");
useEffect(()=>{const controller=new AbortController();fetch("/api/health",{signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(()=>setStatus("Operational")).catch(()=>setStatus("Preview mode"));return()=>controller.abort()},[]);
async function run(){if(scan==="Scanning…")return;setScan("Scanning…");setResult(null);try{const r=await fetch("/api/intelligence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({metric:"Revenue",horizonDays:30})});const j=await r.json().catch(()=>({error:"invalid_server_response"}));if(!r.ok)throw new Error(j.error||"request_failed");setResult(j as Result);setScan("Scan complete")}catch{setScan("Scan unavailable")}finally{window.setTimeout(()=>setScan("Run intelligence scan"),1800)}}
const filteredAlerts=useMemo(()=>alerts.filter(a=>(a.title+" "+a.detail+" "+a.severity).toLowerCase().includes(query.toLowerCase())),[query]);
const filteredConnectors=useMemo(()=>connectors.filter(([name])=>name.toLowerCase().includes(query.toLowerCase())),[query]);
return <div className="app"><aside><div className="brand"><span aria-hidden="true">V</span><div>VEYRA<small>BUSINESS INTELLIGENCE OS</small></div></div><nav aria-label="Primary">{tabs.map(x=><button className={tab===x?"active":""} aria-current={tab===x?"page":undefined} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className="sidebottom"><div className="statusdot" aria-hidden="true"></div><div><b>{status}</b><small>API connection</small></div></div></aside><main><header><div><p className="eyebrow">INTELLIGENCE STUDIO</p><h1>{tab}</h1><p className="muted">Connect your business. Veyra understands it. Veyra tells you what matters.</p></div><div className="header-actions"><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search intelligence" placeholder="Search intelligence…"/><button className="primary" onClick={run} disabled={scan==="Scanning…"}>{scan}</button></div></header>
<section className="metrics">{[["Revenue","£428.3k","+8.4%"],["Cash","£1.82m","+3.1%"],["Pipeline","£1.43m","+17%"],["Risk events","7","2 new"]].map(m=><div className="metric" key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><em>{m[2]}</em></div>)}</section>
{result&&<section className="result" role="status"><div><span className="eyebrow">LIVE BASELINE</span><h2>{result.metric} forecast</h2><p>{result.forecast.value} projected over {result.horizonDays} days · {Math.round(result.forecast.confidence*100)}% confidence</p></div><small>{result.provenance.modelVersion}</small></section>}
{tab==="Alerts"?<section className="panel pagepanel"><div className="panelhead"><div><span className="eyebrow">ALERTS</span><h2>All alerts</h2></div><span className="muted">{filteredAlerts.length} shown</span></div>{filteredAlerts.map(a=><article className="alert" key={a.title}><b className={a.severity.toLowerCase()}>{a.severity}</b><div><strong>{a.title}</strong><p>{a.detail}</p><small>{a.time}</small></div></article>)}</section>:tab==="Data"?<section className="panel pagepanel"><div className="panelhead"><div><span className="eyebrow">DATA LAYER</span><h2>Connected sources</h2></div></div>{filteredConnectors.map(([x,s])=><div className="connector full" key={x}><span className="logo">{x[0]}</span><div><strong>{x}</strong><small>{s}</small></div><b>Healthy</b></div>)}</section>:<><section className="grid"><div className="panel large"><div className="panelhead"><div><span className="eyebrow">MONITOR</span><h2>What changed</h2></div><button onClick={run}>Refresh</button></div><div className="chart"><div className="line l1"></div><div className="line l2"></div><div className="axis"><span>30d ago</span><span>Today</span></div></div></div><div className="panel"><div className="panelhead"><div><span className="eyebrow">ALERTS</span><h2>Needs attention</h2></div><button onClick={()=>setTab("Alerts")}>View all</button></div>{alerts.map(a=><article className="alert" key={a.title}><b className={a.severity.toLowerCase()}>{a.severity}</b><div><strong>{a.title}</strong><p>{a.detail}</p><small>{a.time}</small></div></article>)}</div></section><section className="connectors"><div className="panelhead"><div><span className="eyebrow">DATA LAYER</span><h2>Connected sources</h2></div><button onClick={()=>setTab("Data")}>Manage</button></div>{connectors.map(([x,s])=><div className="connector" key={x}><span className="logo">{x[0]}</span><div><strong>{x}</strong><small>{s}</small></div><b>Healthy</b></div>)}</section></>}
<footer>Veyra Intelligence OS · v1.0.0 · Decision support, not financial advice.</footer></main></div>}

const rootEl = document.getElementById("root");
if (!rootEl) throw new Error("Root element #root not found");
createRoot(rootEl).render(<App />);
